### ISSUE TITLE
Address details not populating for old accounts

### ISSUE THREAD

**Issue by scottybo** [fahrirusliyadi/fr-address-book-for-woocommerce#13]
When a user has an account that was setup prior to the installation of the plugin, they are unable to select their original billing address on the checkout. The shipping address is therefore not selected.

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/07272cb4-3f65-4dd1-bb85-37ca39df394c">

---

And an error gets shown when attempting to checkout:

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/1d3029cf-d806-45c1-ab07-84ff3a4af865">

---

Any ideas what may be causing this? I notice a similar issue from 2020 here: https://github.com/fahrirusliyadi/fr-address-book-for-woocommerce/issues/1

**Comment by scottybo** [comment]
@fahrirusliyadi any thoughts on this? Sorry to chase, but it's causing issues for our client

**Comment by fahrirusliyadi** [comment]
Hi @scottybo, the issue has been fixed in a recent commit. This should take care of the problem.

**Comment by scottybo** [comment]
That's brilliant, thank you - I have tested and can confirm it's working :)

**Comment by scottybo** [comment]
@fahrirusliyadi I've run into another issue with this one - it's not passing over the address country, so when you go to checkout, it says that it's missing the country. Perhaps you could set it to default to the store's settings?

**Comment by fahrirusliyadi** [comment]
Hi @scottybo, I'm sorry I can't reproduce. The address does have the country. Perhaps there is a conflict with other plugins or theme, you can try to deactivate them to check it.
