### ISSUE TITLE
Allow filter $address_fields for farther customize it?

### ISSUE THREAD

**Issue by iwillhappy1314** [fahrirusliyadi/fr-address-book-for-woocommerce#3]
https://github.com/fahrirusliyadi/fr-address-book-for-woocommerce/blob/cf2de82c51b8f26d00ae402b5ba6ad06b34c1a48/src/Fr_Address_Book_for_WooCommerce_Frontend_MyAccount_AddressBookEdit.php#L44

**Comment by fahrirusliyadi** [comment]
You can use <code>woocommerce_default_address_fields</code> filter hook to customize the fields.
