### ISSUE TITLE
Allow edit / create address functionality to be available on /wp-admin/user-edit.php

### ISSUE THREAD

**Issue by fabioelia** [fahrirusliyadi/fr-address-book-for-woocommerce#6]
Admin's or folks with user edit privilege should be able to view / manage user addresses from the wp-admin interface

**Comment by fahrirusliyadi** [comment]
Thanks for the suggestion, but I think the address book will only be used by customers on the front end page. If there's an incorrect billing/shipping address, admins can correct them on the edit order page.
